### ISSUE TITLE
Unexpected behavior on certain inputs

### ISSUE THREAD

**Issue by EpicDavi** [calleerlandsson/pick#196] opened 2017-06-23 18:30 UTC
I recently started playing around with pick (1.6.1) and it's fantastic! I discovered some weird behavior while messing around with it.

Here is an example: `pick -h | pick`. Running this initially results in a blank screen but as characters are inputted, the current string is duplicated until it reaches the top of the screen.

Piping in `pick -h` is probably not a typical use case, but the behavior that results is strange.

EDIT: I am running macOS 10.12.5, if this helps at all.

**Comment by EpicDavi** [comment] 2017-06-23 18:53
This might be related to issue #62 ?

**Comment by calleerlandsson** [comment] 2017-06-24 16:10
Hey @EpicDavi, thanks for trying out pick. I'm happy you like it!

When running `pick -h | pick` from the shell, the `stdout` stream of `pick -h` will be connected to the `stdin` stream of `pick`. Since `pick -h` outputs the usage message to `stderr` rather than to `stdout`, this passes no results to `pick`. That should explain the black screen you see.

To exit pick you can press Ctrl-C. When you do, you should see the usage message that `pick -h` printed to your terminal (which was attached to its `stderr`). You can also type something while pick is running and press Alt-Enter to have pick output that when exiting.

> as characters are inputted, the current string is duplicated until it reaches the top of the screen.

Could you elaborate on this? Maybe upload a screen recording? This does sound like a bug but I can't reproduce it on macOS 10.12.5 running pick from bash in Terminal. Are you running a different shell or terminal emulator?

**Comment by EpicDavi** [comment] 2017-06-24 17:56
Just tried it on another machine (macOs 10.12) and am having the same issue.

However, I tried it on the built-in Terminal (instead of iTerm2) and the issue no longer occurs. This makes me think it is an issue with iTerm2 (3.0.15)?

Anyways, here is what the issue looks like, if you are curious: https://asciinema.org/a/xqJPG5vAVHkkIvNdblbiOuKDJ

**Comment by mptre** [comment] 2017-06-25 07:49
Thanks for the report, I'm able to reproduce this using `xterm(1)`:

```sh
$ pick </dev/null
```

Please try out #198 and see if it solves the problem.

**Comment by mptre** [comment] 2017-06-26 19:18
Fix has been merged, closing for now.

**Closed by mptre** 2017-06-26 19:18 UTC
