### ISSUE TITLE
vim-tmux-navigator stops working when pick runs inside vim

### ISSUE THREAD

**Issue by ggilder** [calleerlandsson/pick#19] opened 2014-12-22 19:48 UTC
I can still switch tmux panes while pick runs in a shell, but if I run vim and then bring up pick inside it, I can no longer navigate to another pane using the [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) key bindings. I'm guessing this might be because the value of `pane_current_command` changes while pick is up?

**Comment by calleerlandsson** [comment] 2015-01-19 09:15
I think this is an effect of #4.

**Comment by calleerlandsson** [comment] 2015-02-26 12:48
@ggilder Could you test this and see if this issue persists after merging #26?

**Comment by Keithbsmiley** [comment] 2015-02-26 17:52
It looks like this isn't a problem anymore but it would still be good if @ggilder could verify.

**Comment by ggilder** [comment] 2015-02-26 18:50
Actually, I am still seeing the problem as of 94180de913e0462ba856d592bb38a7a2f71f2952...

**Comment by calleerlandsson** [comment] 2015-02-26 20:20
@ggilder are you running with the `-X` flag?

**Comment by calleerlandsson** [comment] 2015-02-27 09:43
Since merging #35 (just now) you should not have to pass the `-X` flag anymore.

**Comment by calleerlandsson** [comment] 2015-03-05 12:06
@ggilder Does this issue persist?

**Comment by ggilder** [comment] 2015-03-05 19:35
Tested with 1.1.0, and unfortunately I still see the issue. I tried both with `-X` and without.

**Comment by calleerlandsson** [comment] 2015-03-06 09:30
@ggilder Interesting. What version of Mac OS are you running? I wonder what the difference between your system and @Keithbsmiley's is.

Am I understanding this correctly? This is not really an issue with vim-tmux-navigator (the Vim plugin) since Vim is no longer receiving input. Instead it is a problem with pick and tmux key bindings. When run from the shell in tmux pick does not affect tmux key bindings but when run from vim inside a shell in tmux, tmux key bindings do not work.

**Comment by ggilder** [comment] 2015-03-06 19:28
@calleerlandsson I'm running 10.9.5; I wonder if it might work on 10.10. I don't have a 10.10 system handy to test on unfortunately.

But yes, I think the problem is as you describe: while pick is up in Vim, Vim does not receive input so vim-tmux-navigator hotkeys don't work.

**Comment by Keithbsmiley** [comment] 2015-03-06 20:20
Ah yes I misunderstood what was happening. Pressing `CTRL-J` while pick is open definitely doesn't do what it should in tmux.

**Comment by calleerlandsson** [comment] 2015-03-11 13:46
Me and @teoljungberg tested and can confirm what I stated in my previous comment. I think the problem lies in how running pick from within Vim's `system()` changes how keys behave. selecta, another fuzzy search tool had the same problem when we tested it. Do you guys know a tool that does work?

**Comment by Keithbsmiley** [comment] 2015-03-11 19:25
This does not work in selecta either.

**Comment by mptre** [comment] 2017-08-24 06:17
Digging through old issues, is this still an issue? /cc @keith @ggilder @calleerlandsson

**Comment by keith** [comment] 2017-08-24 15:40
I think the snippet that is now in the README of that repo solves this problem https://github.com/christoomey/vim-tmux-navigator/#add-a-snippet

**Comment by mptre** [comment] 2017-08-24 18:11
Thanks @keith. I will go ahead and close this issue for now. Feel free
to re-open if any errors still is caused by pick.

**Closed by mptre** 2017-08-24 18:11 UTC
Labels: bug
